version: '3'

services:
    # see https://hub.docker.com/_/postgres
    shard1:
        image: postgres:13.4
        command: [ "postgres", "-c", "log_statement=all" ]
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=dbtpcc
        ports:
            - "6432:5432"

    shard2:
        image: postgres:13.4
        command: [ "postgres", "-c", "log_statement=all" ]
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=dbtpcc
        ports:
            - "7432:5432"

    spqr:
        build:
            dockerfile: ./docker/router/Dockerfile
            context: .
        ports:
            - "8432:7432"
        depends_on:
            - shard1
            - shard2