// Code generated by goyacc -o gram.go -p yy gram.y. DO NOT EDIT.

//line gram.y:3
package spqrparser

import __yyfmt__ "fmt"

//line gram.y:3

import (
	"crypto/rand"
	"encoding/hex"
	"strings"
)

func randomHex(n int) (string, error) {
	bytes := make([]byte, n)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes), nil
}

//line gram.y:23
type yySymType struct {
	yys   int
	str   string
	byte  byte
	bytes []byte
	int   int
	bool  bool
	empty struct{}

	statement Statement
	show      *Show

	drop   *Drop
	create *Create

	kill   *Kill
	lock   *Lock
	unlock *Unlock

	ds            *DataspaceDefinition
	kr            *KeyRangeDefinition
	shard         *ShardDefinition
	sharding_rule *ShardingRuleDefinition

	register_router   *RegisterRouter
	unregister_router *UnregisterRouter

	split *SplitKeyRange
	move  *MoveKeyRange
	unite *UniteKeyRange

	shutdown *Shutdown
	listen   *Listen

	trace     *TraceStmt
	stoptrace *StopTraceStmt

	entrieslist []ShardingRuleEntry
	shruleEntry ShardingRuleEntry

	sharding_rule_selector *ShardingRuleSelector
	key_range_selector     *KeyRangeSelector

	colref ColumnRef
	where  WhereClauseNode
}

const IDENT = 57346
const COMMAND = 57347
const SHOW = 57348
const KILL = 57349
const WHERE = 57350
const OR = 57351
const AND = 57352
const TEQ = 57353
const SCONST = 57354
const TSEMICOLON = 57355
const TOPENBR = 57356
const TCLOSEBR = 57357
const SHUTDOWN = 57358
const LISTEN = 57359
const REGISTER = 57360
const UNREGISTER = 57361
const ROUTER = 57362
const ROUTE = 57363
const CREATE = 57364
const ADD = 57365
const DROP = 57366
const LOCK = 57367
const UNLOCK = 57368
const SPLIT = 57369
const MOVE = 57370
const COMPOSE = 57371
const SHARDING = 57372
const COLUMN = 57373
const TABLE = 57374
const HASH = 57375
const FUNCTION = 57376
const KEY = 57377
const RANGE = 57378
const DATASPACE = 57379
const SHARDS = 57380
const KEY_RANGES = 57381
const ROUTERS = 57382
const SHARD = 57383
const HOST = 57384
const SHARDING_RULES = 57385
const RULE = 57386
const COLUMNS = 57387
const VERSION = 57388
const BY = 57389
const FROM = 57390
const TO = 57391
const WITH = 57392
const UNITE = 57393
const ALL = 57394
const ADDRESS = 57395
const CLIENT = 57396
const START = 57397
const STOP = 57398
const TRACE = 57399
const MESSAGES = 57400
const OP = 57401

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"COMMAND",
	"SHOW",
	"KILL",
	"WHERE",
	"OR",
	"AND",
	"TEQ",
	"SCONST",
	"TSEMICOLON",
	"TOPENBR",
	"TCLOSEBR",
	"SHUTDOWN",
	"LISTEN",
	"REGISTER",
	"UNREGISTER",
	"ROUTER",
	"ROUTE",
	"CREATE",
	"ADD",
	"DROP",
	"LOCK",
	"UNLOCK",
	"SPLIT",
	"MOVE",
	"COMPOSE",
	"SHARDING",
	"COLUMN",
	"TABLE",
	"HASH",
	"FUNCTION",
	"KEY",
	"RANGE",
	"DATASPACE",
	"SHARDS",
	"KEY_RANGES",
	"ROUTERS",
	"SHARD",
	"HOST",
	"SHARDING_RULES",
	"RULE",
	"COLUMNS",
	"VERSION",
	"BY",
	"FROM",
	"TO",
	"WITH",
	"UNITE",
	"ALL",
	"ADDRESS",
	"CLIENT",
	"START",
	"STOP",
	"TRACE",
	"MESSAGES",
	"OP",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line gram.y:602

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 177

var yyAct = [...]int{

	109, 94, 134, 106, 63, 115, 133, 26, 27, 100,
	79, 50, 49, 77, 62, 78, 113, 29, 28, 33,
	34, 72, 72, 20, 19, 23, 24, 25, 30, 31,
	72, 98, 72, 89, 160, 159, 152, 140, 88, 118,
	72, 87, 71, 130, 136, 75, 81, 73, 120, 99,
	56, 95, 32, 149, 72, 82, 21, 22, 137, 80,
	74, 154, 54, 116, 61, 85, 86, 52, 76, 104,
	90, 91, 158, 156, 93, 96, 36, 40, 102, 101,
	92, 103, 105, 103, 97, 39, 42, 95, 110, 111,
	112, 43, 38, 41, 70, 114, 117, 44, 48, 69,
	37, 84, 119, 123, 121, 72, 47, 59, 125, 124,
	35, 126, 72, 46, 143, 51, 65, 138, 131, 1,
	132, 45, 107, 139, 64, 141, 142, 18, 123, 17,
	16, 15, 144, 125, 124, 145, 147, 150, 151, 146,
	55, 57, 14, 128, 12, 153, 66, 67, 68, 147,
	129, 13, 8, 9, 148, 157, 135, 155, 6, 5,
	161, 162, 4, 163, 164, 3, 7, 11, 10, 60,
	58, 53, 2, 108, 127, 122, 83,
}
var yyPact = [...]int{

	1, -1000, 63, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 56,
	56, -45, -46, 32, 15, 15, 103, 10, 112, -1000,
	15, 15, 15, 79, 74, -1000, -1000, -1000, -1000, -1000,
	-1000, 101, 3, 24, 18, -1000, -1000, -1000, -1000, -39,
	-48, -1000, 23, -1000, 2, -1000, 19, -1000, 93, -1000,
	112, 112, -1000, -1000, -1000, -1000, -7, -11, -17, 101,
	28, -1000, -1000, 50, 36, -19, 7, -49, 101, -1000,
	26, 17, 101, -1000, 108, -1000, -1000, 101, 101, 101,
	-37, -1000, -1000, 14, 31, 101, -9, 112, 6, 112,
	-1000, -1000, -1000, -1000, -1000, -1000, 124, 108, 139, -1000,
	-4, -1000, -1000, 112, 31, 13, 101, -1000, 112, -12,
	112, -1000, 108, -1000, -1000, -1000, 99, 112, -1000, -1000,
	112, -1000, 13, 13, -1000, 20, 101, 101, -1000, -13,
	112, -1000, 124, -1000, -1000, -1000, 13, -1000, -1000, 27,
	-1000, -1000, 112, 52, 101, 51, -14, -1000, -15, 101,
	101, 14, 14, -1000, -1000,
}
var yyPgo = [...]int{

	0, 176, 3, 175, 174, 173, 4, 0, 172, 171,
	115, 170, 169, 168, 167, 166, 165, 162, 159, 158,
	100, 92, 85, 77, 6, 2, 5, 156, 154, 1,
	153, 152, 151, 144, 142, 131, 130, 129, 127, 119,
	110,
}
var yyR1 = [...]int{

	0, 39, 40, 40, 8, 8, 8, 8, 8, 8,
	8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
	6, 6, 7, 3, 3, 3, 4, 4, 5, 2,
	2, 2, 1, 1, 11, 12, 15, 15, 15, 15,
	16, 16, 16, 16, 18, 18, 19, 17, 17, 17,
	17, 13, 31, 20, 21, 21, 24, 24, 25, 26,
	26, 27, 27, 28, 28, 29, 29, 22, 22, 23,
	23, 30, 9, 10, 34, 14, 14, 35, 36, 33,
	32, 37, 38, 38,
}
var yyR2 = [...]int{

	0, 2, 0, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	3, 3, 0, 2, 1, 1, 2, 4, 2, 4,
	2, 2, 2, 2, 4, 4, 3, 2, 2, 2,
	2, 3, 2, 2, 6, 5, 1, 2, 2, 2,
	0, 2, 2, 3, 0, 2, 0, 11, 10, 5,
	4, 2, 3, 3, 6, 3, 3, 4, 4, 2,
	1, 5, 3, 3,
}
var yyChk = [...]int{

	-1000, -39, -8, -16, -17, -18, -19, -15, -31, -30,
	-13, -14, -33, -32, -34, -35, -36, -37, -38, 23,
	22, 55, 56, 24, 25, 26, 6, 7, 17, 16,
	27, 28, 51, 18, 19, -40, 13, -20, -21, -22,
	-23, 37, 30, 35, 41, -20, -21, -22, -23, 57,
	57, -10, 35, -9, 30, -10, 35, -10, -11, 4,
	-12, 54, 4, -6, 12, 4, -10, -10, -10, 20,
	20, -7, 4, 44, 36, -7, 50, 52, 54, 58,
	36, 44, 36, -1, 8, -6, -6, 48, 49, 50,
	-7, -7, 52, -7, -29, 37, -7, 48, 50, 42,
	58, -7, 52, -7, 52, -7, -2, 14, -5, -7,
	-7, -7, -7, 53, -29, -26, 32, -7, 48, -6,
	42, -6, -3, 4, 10, 9, -2, -4, 4, 11,
	47, -6, -26, -24, -25, -27, 31, 45, -7, -6,
	49, -6, -2, 15, -6, -6, -24, -25, -28, 33,
	-7, -7, 49, -6, 34, -6, 21, -7, 21, 49,
	49, -7, -7, -29, -29,
}
var yyDef = [...]int{

	0, -2, 2, 4, 5, 6, 7, 8, 9, 10,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 80,
	0, 0, 0, 0, 0, 1, 3, 40, 41, 42,
	43, 0, 0, 0, 0, 47, 48, 49, 50, 0,
	0, 36, 0, 38, 0, 52, 0, 71, 32, 34,
	0, 0, 35, 79, 20, 21, 0, 0, 0, 0,
	0, 53, 22, 66, 0, 0, 0, 0, 0, 46,
	0, 0, 0, 51, 0, 75, 76, 0, 0, 0,
	0, 82, 83, 66, 60, 0, 0, 0, 0, 0,
	44, 45, 37, 73, 39, 72, 33, 0, 0, 28,
	0, 77, 78, 0, 60, 0, 0, 65, 0, 0,
	0, 70, 0, 23, 24, 25, 0, 0, 26, 27,
	0, 81, 0, 55, 56, 64, 0, 0, 59, 0,
	0, 69, 31, 29, 30, 74, 54, 57, 58, 0,
	61, 62, 0, 0, 0, 0, 0, 63, 0, 0,
	0, 66, 66, 68, 67,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:166
		{
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:167
		{
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:172
		{
			setParseTree(yylex, yyDollar[1].create)
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:176
		{
			setParseTree(yylex, yyDollar[1].create)
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:180
		{
			setParseTree(yylex, yyDollar[1].trace)
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:184
		{
			setParseTree(yylex, yyDollar[1].stoptrace)
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:188
		{
			setParseTree(yylex, yyDollar[1].drop)
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:192
		{
			setParseTree(yylex, yyDollar[1].lock)
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:196
		{
			setParseTree(yylex, yyDollar[1].unlock)
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:200
		{
			setParseTree(yylex, yyDollar[1].show)
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:204
		{
			setParseTree(yylex, yyDollar[1].kill)
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:208
		{
			setParseTree(yylex, yyDollar[1].listen)
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:212
		{
			setParseTree(yylex, yyDollar[1].shutdown)
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:216
		{
			setParseTree(yylex, yyDollar[1].split)
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:220
		{
			setParseTree(yylex, yyDollar[1].move)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:224
		{
			setParseTree(yylex, yyDollar[1].unite)
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:228
		{
			setParseTree(yylex, yyDollar[1].register_router)
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:232
		{
			setParseTree(yylex, yyDollar[1].unregister_router)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:237
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:241
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:246
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:252
		{
			yyVAL.str = yyDollar[1].str
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:254
		{
			yyVAL.str = "AND"
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:256
		{
			yyVAL.str = "OR"
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:261
		{
			yyVAL.str = yyDollar[1].str
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:263
		{
			yyVAL.str = "="
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:269
		{
			yyVAL.colref = ColumnRef{
				ColName: yyDollar[1].str,
			}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:277
		{
			yyVAL.where = yyDollar[2].where
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:280
		{
			yyVAL.where = WhereClauseLeaf{
				ColRef: yyDollar[1].colref,
				Op:     yyDollar[2].str,
				Value:  yyDollar[3].str,
			}
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:288
		{
			yyVAL.where = WhereClauseOp{
				Op:    yyDollar[2].str,
				Left:  yyDollar[1].where,
				Right: yyDollar[3].where,
			}
		}
	case 32:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:298
		{
			yyVAL.where = WhereClauseEmpty{}
		}
	case 33:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:302
		{
			yyVAL.where = yyDollar[2].where
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:309
		{
			switch v := strings.ToLower(string(yyDollar[1].str)); v {
			case DatabasesStr, RoutersStr, PoolsStr, ShardsStr, BackendConnectionsStr, KeyRangesStr, ShardingRules, ClientsStr, StatusStr, VersionStr:
				yyVAL.str = v
			default:
				yyVAL.str = UnsupportedStr
			}
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:320
		{
			switch v := string(yyDollar[1].str); v {
			case ClientStr:
				yyVAL.str = v
			default:
				yyVAL.str = "unsupp"
			}
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:331
		{
			yyVAL.drop = &Drop{Element: yyDollar[2].key_range_selector}
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:336
		{
			yyVAL.drop = &Drop{Element: &KeyRangeSelector{KeyRangeID: `*`}}
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:340
		{
			yyVAL.drop = &Drop{Element: yyDollar[2].sharding_rule_selector}
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:345
		{
			yyVAL.drop = &Drop{Element: &ShardingRuleSelector{ID: `*`}}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:351
		{
			yyVAL.create = &Create{Element: yyDollar[2].ds}
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:356
		{
			yyVAL.create = &Create{Element: yyDollar[2].sharding_rule}
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:361
		{
			yyVAL.create = &Create{Element: yyDollar[2].kr}
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:365
		{
			yyVAL.create = &Create{Element: yyDollar[2].shard}
		}
	case 44:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:372
		{
			yyVAL.trace = &TraceStmt{All: true}
		}
	case 45:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:375
		{
			yyVAL.trace = &TraceStmt{
				Client: yyDollar[4].str,
			}
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:383
		{
			yyVAL.stoptrace = &StopTraceStmt{}
		}
	case 47:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:390
		{
			yyVAL.create = &Create{Element: yyDollar[2].ds}
		}
	case 48:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:395
		{
			yyVAL.create = &Create{Element: yyDollar[2].sharding_rule}
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:400
		{
			yyVAL.create = &Create{Element: yyDollar[2].kr}
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:404
		{
			yyVAL.create = &Create{Element: yyDollar[2].shard}
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:411
		{
			yyVAL.show = &Show{Cmd: yyDollar[2].str, Where: yyDollar[3].where}
		}
	case 52:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:417
		{
			yyVAL.lock = &Lock{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID}
		}
	case 53:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:425
		{
			yyVAL.ds = &DataspaceDefinition{ID: yyDollar[2].str}
		}
	case 54:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:431
		{
			yyVAL.sharding_rule = &ShardingRuleDefinition{ID: yyDollar[3].str, TableName: yyDollar[5].str, Entries: yyDollar[6].entrieslist, Dataspace: yyDollar[4].str}
		}
	case 55:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:436
		{
			str, err := randomHex(6)
			if err != nil {
				panic(err)
			}
			yyVAL.sharding_rule = &ShardingRuleDefinition{ID: "shrule" + str, TableName: yyDollar[4].str, Entries: yyDollar[5].entrieslist, Dataspace: yyDollar[3].str}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:445
		{
			yyVAL.entrieslist = make([]ShardingRuleEntry, 0)
			yyVAL.entrieslist = append(yyVAL.entrieslist, yyDollar[1].shruleEntry)
		}
	case 57:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:451
		{
			yyVAL.entrieslist = append(yyDollar[1].entrieslist, yyDollar[2].shruleEntry)
		}
	case 58:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:457
		{
			yyVAL.shruleEntry = ShardingRuleEntry{
				Column:       yyDollar[1].str,
				HashFunction: yyDollar[2].str,
			}
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:466
		{
			yyVAL.str = yyDollar[2].str
		}
	case 60:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:469
		{
			yyVAL.str = ""
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:473
		{
			yyVAL.str = yyDollar[2].str
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:478
		{
			yyVAL.str = yyDollar[2].str
		}
	case 63:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:484
		{
			yyVAL.str = yyDollar[3].str
		}
	case 64:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:487
		{
			yyVAL.str = ""
		}
	case 65:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:490
		{
			yyVAL.str = yyDollar[2].str
		}
	case 66:
		yyDollar = yyS[yypt-0 : yypt+1]
//line gram.y:493
		{
			yyVAL.str = "default"
		}
	case 67:
		yyDollar = yyS[yypt-11 : yypt+1]
//line gram.y:498
		{
			yyVAL.kr = &KeyRangeDefinition{LowerBound: []byte(yyDollar[5].str), UpperBound: []byte(yyDollar[7].str), ShardID: yyDollar[10].str, KeyRangeID: yyDollar[3].str, Dataspace: yyDollar[11].str}
		}
	case 68:
		yyDollar = yyS[yypt-10 : yypt+1]
//line gram.y:502
		{
			str, err := randomHex(6)
			if err != nil {
				panic(err)
			}
			yyVAL.kr = &KeyRangeDefinition{LowerBound: []byte(yyDollar[4].str), UpperBound: []byte(yyDollar[6].str), ShardID: yyDollar[9].str, KeyRangeID: "kr" + str, Dataspace: yyDollar[10].str}
		}
	case 69:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:513
		{
			yyVAL.shard = &ShardDefinition{Id: yyDollar[2].str, Hosts: []string{yyDollar[5].str}}
		}
	case 70:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:518
		{
			str, err := randomHex(6)
			if err != nil {
				panic(err)
			}
			yyVAL.shard = &ShardDefinition{Id: "shard" + str, Hosts: []string{yyDollar[4].str}}
		}
	case 71:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:529
		{
			yyVAL.unlock = &Unlock{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID}
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:535
		{
			yyVAL.sharding_rule_selector = &ShardingRuleSelector{ID: yyDollar[3].str}
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:541
		{
			yyVAL.key_range_selector = &KeyRangeSelector{KeyRangeID: yyDollar[3].str}
		}
	case 74:
		yyDollar = yyS[yypt-6 : yypt+1]
//line gram.y:547
		{
			yyVAL.split = &SplitKeyRange{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID, KeyRangeFromID: yyDollar[4].str, Border: []byte(yyDollar[6].str)}
		}
	case 75:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:553
		{
			yyVAL.kill = &Kill{Cmd: yyDollar[2].str, Target: yyDollar[3].str}
		}
	case 76:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:556
		{
			yyVAL.kill = &Kill{Cmd: "client", Target: yyDollar[3].str}
		}
	case 77:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:562
		{
			yyVAL.move = &MoveKeyRange{KeyRangeID: yyDollar[2].key_range_selector.KeyRangeID, DestShardID: yyDollar[4].str}
		}
	case 78:
		yyDollar = yyS[yypt-4 : yypt+1]
//line gram.y:568
		{
			yyVAL.unite = &UniteKeyRange{KeyRangeIDL: yyDollar[2].key_range_selector.KeyRangeID, KeyRangeIDR: yyDollar[4].str}
		}
	case 79:
		yyDollar = yyS[yypt-2 : yypt+1]
//line gram.y:574
		{
			yyVAL.listen = &Listen{addr: yyDollar[2].str}
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
//line gram.y:580
		{
			yyVAL.shutdown = &Shutdown{}
		}
	case 81:
		yyDollar = yyS[yypt-5 : yypt+1]
//line gram.y:588
		{
			yyVAL.register_router = &RegisterRouter{ID: yyDollar[3].str, Addr: yyDollar[5].str}
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:594
		{
			yyVAL.unregister_router = &UnregisterRouter{ID: yyDollar[3].str}
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line gram.y:599
		{
			yyVAL.unregister_router = &UnregisterRouter{ID: `*`}
		}
	}
	goto yystack /* stack new state and value */
}
