
addr: '[spqr_router_1_1]:6432'
adm_addr: '[spqr_router_1_1]:7432'
proto: 'tcp'
http_addr: 'spqr_router_1_1:7000'
data_folder: '/etc/pkg'

executer:
        init_sql_path: "/pkg/docker/pkg/init.sql"

qrouter:
        qrouter_type: PROXY
router:
        tls:
                key_file: '/etc/odyssey/ssl/server.key'
                cert_file: '/etc/odyssey/ssl/server.crt' 
                sslmode: "disable" 
        frontend_rules:
                - route_key_cfg:
                        usr: user1
                        db: db1
                  pooling_mode: TRANSACTION
                  auth_rule:
                          auth_method: 'ok'
        proto: 'tcp6'
        shard_mapping:
                sh1: 
                        tls:
                                key_file: '/etc/odyssey/ssl/server.key'
                                sslmode: "disable" 
                                cert_file: '/etc/odyssey/ssl/server.crt' 
                        conn_db: "db1"
                        conn_usr: "user1"
                        passwd: 12345678
                        hosts:
                            - conn_addr: "192.168.233.02:6432"
                sh2: 
                        tls:
                                key_file: '/etc/odyssey/ssl/server.key'
                                sslmode: "disable"
                                cert_file: '/etc/odyssey/ssl/server.crt' 
                        conn_db: "db1"
                        conn_usr: "user1"
                        passwd: 12345678
                        hosts:
                            - conn_addr: "192.168.233.03:6432"

        backend_rules:
                - route_key_cfg:
                        usr: user1
                        db: db1
                  pool_discard: true
                  pool_rollback: true
